// flow-typed signature: eec2de1255ef6a0e4e5a044746046901
// flow-typed version: <<STUB>>/razzle-dev-utils_v^0.8.4/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'razzle-dev-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'razzle-dev-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'razzle-dev-utils/FriendlyErrorsPlugin' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/logger' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/printErrors' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/webpackHotDevClient' {
  declare module.exports: any;
}

// Filename aliases
declare module 'razzle-dev-utils/FriendlyErrorsPlugin.js' {
  declare module.exports: $Exports<'razzle-dev-utils/FriendlyErrorsPlugin'>;
}
declare module 'razzle-dev-utils/logger.js' {
  declare module.exports: $Exports<'razzle-dev-utils/logger'>;
}
declare module 'razzle-dev-utils/printErrors.js' {
  declare module.exports: $Exports<'razzle-dev-utils/printErrors'>;
}
declare module 'razzle-dev-utils/webpackHotDevClient.js' {
  declare module.exports: $Exports<'razzle-dev-utils/webpackHotDevClient'>;
}
